version: '3.9'

networks:
  microfrontends_network:
    name: microfrontends_network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.168.0.0/24"

services:
  base:
    image: speakyourownideas/base:prod
    build:
      context: .
      dockerfile: ./Dockerfile

  auth:
    image: speakyourownideas/auth:prod
    container_name: microfrontends_auth
    build:
      context: ./apps/auth
      dockerfile: ./deployments/auth.dockerfile
    ports:
      - "3002:3002"
    # env_file:
    #   ./apps/auth/.env.development
    extra_hosts:
      - "auth.speakyourownideas.com:127.0.0.1"
      - "posts.speakyourownideas.com:172.168.0.3"
    networks:
      microfrontends_network:
        ipv4_address: "172.168.0.2"

  posts:
    image: speakyourownideas/posts:prod
    container_name: microfrontends_posts
    build:
      context: ./apps/posts
      dockerfile: ./deployments/posts.dockerfile
    ports:
      - "3001:3001"
    # env_file:
    #   ./apps/posts/.env.development
    extra_hosts:
      - "posts.speakyourownideas.com:127.0.0.1"
      - "auth.speakyourownideas.com:172.168.0.2"
    networks:
      microfrontends_network:
        ipv4_address: "172.168.0.3"

  shell:
    image: speakyourownideas/shell:prod
    container_name: microfrontends_shell
    build:
      context: ./apps/shell
      dockerfile: ./deployments/shell.dockerfile
    ports:
      - "3000:3000"
    # env_file:
    #   ./apps/shell/.env.development
    extra_hosts:
      - "auth.speakyourownideas.com:172.168.0.2"
      - "posts.speakyourownideas.com:172.168.0.3"
    networks:
      microfrontends_network:
        ipv4_address: "172.168.0.4"
