version: "3.9"

networks:
  backend:
    name: application-shell-network
volumes:
  aws-data:
    name: application-shell-aws-data

services:
  aws:
    container_name: application-shell-aws
    image: localstack/localstack-light:0.14.0
    environment:
      - SERVICES=s3
      - EDGE_PORT=4566
      - DATA_DIR=/tmp/localstack/data
    ports:
      - "4566:4566"
    volumes:
      - type: volume
        source: aws-data
        target: /tmp/localstack/data
    networks:
      - backend
